### PR TITLE
add package and setup.py file

### PR DESCRIPTION
**Pull request by GreatBahram**
Hi 
I changed the package structure to be able to put it on pypi and I think it'd be better to add cli for this package instead of just running it ( i've forgotten to say I did that for linux version).

have fun

### CODE REVIEW

**Comment by GiacomoLaw** [comment]
In addition, please make sure all documentation files are up to date 🙂

Thanks!

**Comment by GreatBahram** [comment]
Hi dude, 
In the past, you could only clone the repository and then run the python file. in this version, first you should upload the code on pypi and then the users only need the install this package via their package manager (`pip install keylogger`).
That's it. There is no need to copy or clone or even install its dependencies. all of that handles by python package. if it would be possible please add cli in its todo file. since right now you should call the program with some environmental variable in order to control it. So it think, a cli can be very useful.

**Comment by GiacomoLaw** [comment]
I'll distribute it later today to Pypi.

**Comment by GreatBahram** [comment]
My pleasure, good luck bro

**Pull request merged**
