### PR TITLE
.travis.yml updated to do something

### PR DESCRIPTION
**Pull request by isivisi**
You don't seem to have any tests so I just got it to built and run the program on both linux and mac.  The linux version doesn't seem to pass because the Xlib module isn't found even though I made it install python-xlib. The mac version hasn't been run because the queue times are really long.

for issue #3

### CODE REVIEW

**Comment by GiacomoLaw** [comment]
So this will fix the broken tests on Travis?

**Comment by isivisi** [comment]
This actually tries to build and run your app on travis. It only tests to see if the building and running of the app work, doesn't check for anything specific.

**Comment by GiacomoLaw** [comment]
Awesome! Thanks for the great help 😄

**Comment by GiacomoLaw** [comment]
Getting an error here: https://travis-ci.org/GiacomoLaw/Keylogger/jobs/180489969

**Pull request merged**
