### PR TITLE
Update readme file

### PR DESCRIPTION
**Pull request by GreatBahram**

### CODE REVIEW

**Comment by GiacomoLaw** [comment]
Here you go: https://pypi.org/manage/project/keylogger/releases/

Need to edit the setup and then update.

**Comment by GreatBahram** [comment]
Thanks dude, I've just updated readme file and setup.py file to show that document correctly on pypi website.

**Comment by GiacomoLaw** [comment]
Awesome, thanks. Do I have to update to PyPi again?

**Comment by GreatBahram** [comment]
Unfortunately, Yes!

**Comment by GreatBahram** [comment]
Don't forget you should increase the version number otherwise the pypi does not accept the new package

**Comment by GreatBahram** [comment]
@GiacomoLaw  hold on a second, let me add 'changelog file` too. then push the update

**Comment by GiacomoLaw** [comment]
Ok, I will do that when I'm at my computer later today.

**Comment by GreatBahram** [comment]
OK, that's a problem at all.

**Pull request merged**
