### PR TITLE
Replaced switch statement with preprocessor statements 

### PR DESCRIPTION
**Pull request by AbsoluteVacuum**
The code now does not check FORMAT after every press. It now compiles directly to the required option instead. Thus the compiled program must now be both faster and smaller.

### CODE REVIEW

**Comment by GiacomoLaw** [comment]
Any chance you could resolve the conflicts so I can push?

**Comment by AbsoluteVacuum** [comment]
> Any chance you could resolve the conflicts so I can push? Thanks

Please review the changes, must be it.

**Comment by GiacomoLaw** [comment]
Thanks!

**Comment by AbsoluteVacuum** [comment]
Please review my latest fix, I uploaded this version by mistake

6 сентября 2021, 06:41:16, от "Giacomo Lawrance" ***@***.***>:


Thanks!
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request merged**
